
spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3309/warehouse_management_system?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
server:
  port: 12345
mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.design. warehouseManagementSystem.pojo
  configuration:
    map-underscore-to-camel-case: true
